[lint]
select = [
    'E',
    'W',
    'F',
    'I',
    'N',
    'UP',
    'B',
    'SIM',
    'RUF',
]
ignore = [
    'E501',
    'RUF001',
    'RUF002',
    'RUF003',
]
allowed-confusables = [
    '，', '。', '：', '；',
    '（', '）', '！', '？',
    '、', '“', '”', '‘',
    '’', '【', '】', '—',
    '–',
]

[lint.isort]
known-first-party = ['app', 'shared']

[format]
quote-style = 'double'
indent-style = 'space'
line-ending = 'auto'
